version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=massimostanzione_isw2-deliverable2

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
